# Comparisons between two portfolios - example

This is an example of a comparative analysis between 2 portfolios.

We start by importing **azapy** and other useful packages.

In [18]:
import azapy as az

print(f"azapy version {az.version()} >= 1.2.0")

azapy version 1.2.6 >= 1.2.0

### Load historical market data for 2 different portfolios

The 2 sets of portfolio components are listed in `symb1` and `symb2`, respectively.

>Make sure that `mktdir` holds a convenient location to save the market data.
>You can inhibit the saving mechanism by setting `save=False` in the call of `az.readMkT` function (_see `readMkT` documentation_ https://azapy.readthedocs.io/en/latest/)

In [19]:
symb1 = ['GLD', 'TLT', 'XLV', 'SPY', 'VHT']
symb2 = ['PFG', 'QQQ', 'SPY', 'XLF', 'ONEQ']

sdate = "2012-01-01"
edate = "today"

mktdir = "../MkTdata"

mktdata1 = az.readMkT(symb1, sdate=sdate, edate=edate, file_dir=mktdir) 
mktdata2 = az.readMkT(symb2, sdate=sdate, edate=edate, file_dir=mktdir)

read GLD data from file
read TLT data from file
read XLV data from file
read SPY data from file
read VHT data from file

Request between 2012-01-03 : 2026-05-05
                    GLD         TLT         XLV         SPY         VHT
source            yahoo       yahoo       yahoo       yahoo       yahoo
force             False       False       False       False       False
save               True        True        True        True        True
file_dir     ../MkTdata  ../MkTdata  ../MkTdata  ../MkTdata  ../MkTdata
file_format         csv         csv         csv         csv         csv
api_key            None        None        None        None        None
nrow               3605        3605        3605        3605        3605
sdate        2012-01-03  2012-01-03  2012-01-03  2012-01-03  2012-01-03
edate        2026-05-05  2026-05-05  2026-05-05  2026-05-05  2026-05-05
error                No          No          No          No          No
extraction time 0.301 s
read PFG data from file
read QQQ data from file
read SPY data from file
read XLF data from file
read ONEQ data from file

Request between 2012-01-03 : 2026-05-05
                    PFG         QQQ         SPY         XLF        ONEQ
source            yahoo       yahoo       yahoo       yahoo       yahoo
force             False       False       False       False       False
save               True        True        True        True        True
file_dir     ../MkTdata  ../MkTdata  ../MkTdata  ../MkTdata  ../MkTdata
file_format         csv         csv         csv         csv         csv
api_key            None        None        None        None        None
nrow               3605        3605        3605        3605        3605
sdate        2012-01-03  2012-01-03  2012-01-03  2012-01-03  2012-01-03
edate        2026-05-05  2026-05-05  2026-05-05  2026-05-05  2026-05-05
error                No          No          No          No          No
extraction time 0.25 s

### Check the historical market data quality for fist portfolio

We use the **azapy** function `summary_MktData`. It returns:

- `symbol` the symbols included in `mktdata1`. These are the portfolio components, 
- `begin` is the beginning of the historical time-series for each symbol,
- `end` is the end date of the historical time series (the most recent date),
- `length` is history length in number of business days.
- `na_total` is the total number of missing values, `nan`,
- `na_b` is the total number of missing records at the beginning of the time-series (in number of business days),
- `na_e` is the total number of missing records at the end of the time-series (in number of business days),
- `cont` is the total number of missing records (at the beginning, end and in the middle of the time-series). 

We are looking for `na_total`, `na_b`, `na_e` and `count` to be `0`. Missing data could be a serious problem. In general gaps in the market data should be filled before proceeding further. 

*For more information see the documentation for `summary_MkTData`.*

In [20]:
az.summary_MkTdata(mktdata1)

  symbol      begin        end  length  na_total  na_b  na_e  cont
0    GLD 2012-01-03 2026-05-05    3605         0     0     0     0
1    SPY 2012-01-03 2026-05-05    3605         0     0     0     0
2    TLT 2012-01-03 2026-05-05    3605         0     0     0     0
3    VHT 2012-01-03 2026-05-05    3605         0     0     0     0
4    XLV 2012-01-03 2026-05-05    3605         0     0     0     0

### Check the historical market data quality for second portfolio

Same as before.

In [21]:
az.summary_MkTdata(mktdata2)

  symbol      begin        end  length  na_total  na_b  na_e  cont
0   ONEQ 2012-01-03 2026-05-05    3605         0     0     0     0
1    PFG 2012-01-03 2026-05-05    3605         0     0     0     0
2    QQQ 2012-01-03 2026-05-05    3605         0     0     0     0
3    SPY 2012-01-03 2026-05-05    3605         0     0     0     0
4    XLF 2012-01-03 2026-05-05    3605         0     0     0     0

### Set the dispersion measure parameters.

In our case we have chosen mCVaR (mixture of 3 CVaR's) dispersion measure. A similar workflow holds for any other dispersion measure.

In [22]:
alpha = [0.95, 0.90, 0.85]
coef = [0.2, 0.3, 0.5]

### Setup the first portfolio 

Two steps:

1. Construct the portfolio class. In our case this is `az.Port_CVaR`.
2. Set the model and trigger the computation of the portfolio time-series
   (in this case rtype='Sharpe' and mu0=0 - the default values).

*For more information see the documentation for `Port_CVaR` class*.

In [23]:
pr1 = az.Port_CVaR(mktdata1, pname='Port1')
port1 = pr1.set_model(alpha=alpha, coef=coef)

### Setup the second portfolio

Same as above.

In [24]:
pr2 = az.Port_CVaR(mktdata2, pname='Port2')
port2 = pr2.set_model(alpha=alpha, coef=coef)

### Setup a `Port_Simple` class to compare the 2 portfolios

The `Port_Simple` class is set from the list of portfolios time-series. 

>Note the must call to `set_model` method.

>Observation: `Port_Simple` is the class that supports the back testing of "Buy and Hold" portfolio (_see its documentation_).
It also can be used as a tool to compare the performance of multiple portfolios. Here we use it in this latter capacity.

In [25]:
pp = az.Port_Simple([port1, port2])
_ = pp.set_model()

### Visualized the 2 portfolios time-series

> Note the use of flag `fancy=True`. It designates the use of *plotly* package for interactive time-series. 

As expected, `Port2` is more aggressive than `Port1`.

In [26]:
_ = pp.port_view_all(componly=True, fancy=True, title="Reltive performance")

### Compare the performances of the two portfolios

- `RR` is the average annual portfolio rate of returns.
- `DD` is the maximum drawdown rate.
- `Beta` is the ratio `RR/DD`.
- `DD_date` is the date of maximum drawdown.
- `DD_start` is the date when the maximum drawdown event had started.
- `DD_end` is the date when the maximum drawdown event had ended. If it is `NaN` then the drawdown is still in progress (`DD` and `DD_date` are only provisional).

> Note the use of flag `fancy=True` - the rates are reported in percent with 2 decimals.

The rate of returns for `Port2` is almost double than for `Port1`. However, the maximum drawdown is 50% larger for `Port2` than for `Port1`.

In [27]:
pp.port_perf(componly=True, fancy=True)

           RR     DD     RoMaD     DD_date    DD_start      DD_end  DD_days
symbol
Port2   14.95 -33.68  0.444019  2022-12-28  2021-11-19  2024-03-27      859
Port1    9.57 -22.21  0.430984  2022-09-27  2021-11-12  2024-05-15      915

### Compare the portfolios annual returns 

Except for 2018, `Port2` has significantly higher returns than `Port1`.
This report can be detailed further by asking for the monthly returns. In this case it is worth to investigate separately the performance of the two portfolios.

In [28]:
pp.port_annual_returns(withcomp=True, componly=True, fancy=True)

### First portfolio performance (details)

Note that the portfolio drawdown is smaller than any individual component drawdown. Thus, `Port1` has a good diversification for a moderate average return.

In [29]:
pr1.port_perf(fancy=True)

           RR     DD     RoMaD     DD_date    DD_start      DD_end  DD_days
symbol
Port1    9.57 -22.21  0.430984  2022-09-27  2021-11-12  2024-05-15      915
SPY     14.89 -33.72  0.441738  2020-03-23  2020-02-19  2020-08-10      173
XLV     12.28 -28.40  0.432176  2020-03-23  2020-01-22  2020-07-15      175
VHT     12.37 -28.85  0.428857  2020-03-23  2020-02-19  2020-06-08      110
GLD      7.14 -42.11  0.169582  2015-12-17  2012-10-04  2020-07-22     2848
TLT      0.41 -48.35  0.008530  2023-10-19  2020-08-04         NaN     2100

### First portfolio drawdown (details)

Subsequent drawdowns are smaller but still above 10%.

In [30]:
pr1.port_drawdown(fancy=True)

       DD        Date       Start         End  NrDays
No
1  -22.21  2022-09-27  2021-11-12  2024-05-15     915
2  -17.97  2020-03-20  2020-02-21  2020-04-23      62
3  -16.71  2015-09-28  2015-08-05  2016-06-30     330
4  -16.21  2026-03-30  2026-01-29         NaN      96
5  -13.59  2018-12-24  2018-08-29  2019-01-31     155

### First portfolio rebalancing weights

Note that recently the portfolio is dominated by GLD. From the beginning of 2020 GLD is over 40%.

In [31]:
pr1.get_weights(fancy=True)

        Droll       Dfix    GLD    TLT    XLV    SPY    VHT
0  2015-06-25 2015-06-24   0.00  10.29  89.71   0.00   0.00
1  2015-09-25 2015-09-24   0.00  16.05  55.59   0.00  28.36
2  2015-12-28 2015-12-24   0.00  29.29  34.11  36.60   0.00
3  2016-03-28 2016-03-24   0.00  40.57  46.32  13.12   0.00
4  2016-06-27 2016-06-24   0.00  40.23  39.51  20.25   0.00
5  2016-09-27 2016-09-26   0.00  46.49  37.11  16.40   0.00
6  2016-12-27 2016-12-23   0.00  35.10   0.00  64.90   0.00
7  2017-03-28 2017-03-27   0.00  33.23   0.00  66.77   0.00
8  2017-06-27 2017-06-26   0.00  33.14   0.00  66.86   0.00
9  2017-09-26 2017-09-25   0.00  33.08   0.00  66.92   0.00
10 2017-12-26 2017-12-22   0.00  32.16   0.00  67.84   0.00
11 2018-03-26 2018-03-23   0.00  29.37   0.00  70.63   0.00
12 2018-06-26 2018-06-25   0.00  30.14   0.00  69.86   0.00
13 2018-09-25 2018-09-24   0.00  28.62   0.00  71.38   0.00
14 2018-12-26 2018-12-24  31.11   0.00   4.73  64.16   0.00
15 2019-03-26 2019-03-25  37.31   0.00   0.00  62.69   0.00
16 2019-06-25 2019-06-24  33.63   0.00   0.00  66.37   0.00
17 2019-09-25 2019-09-24  36.97   0.00   0.00  63.03   0.00
18 2019-12-26 2019-12-24  45.75   5.29  12.80  36.16   0.00
19 2020-03-26 2020-03-25  37.94  30.58   7.64   1.16  22.69
20 2020-06-25 2020-06-24  37.63  32.12   4.67   0.00  25.57
21 2020-09-25 2020-09-24  40.03  29.67   0.00   2.90  27.40
22 2020-12-28 2020-12-24  40.54  26.14   0.00   1.65  31.67
23 2021-03-26 2021-03-25  44.62  16.64   0.00  18.38  20.37
24 2021-06-25 2021-06-24  39.11  16.65  20.72  23.52   0.00
25 2021-09-27 2021-09-24  48.72  11.29  11.19  28.80   0.00
26 2021-12-28 2021-12-27  15.68  36.99   0.00  47.33   0.00
27 2022-03-28 2022-03-25  47.51  12.04   0.00  40.45   0.00
28 2022-06-27 2022-06-24  52.78   0.00  47.22   0.00   0.00
29 2022-09-27 2022-09-26  27.86   0.00  72.14   0.00   0.00
30 2022-12-27 2022-12-23  21.62   0.00  78.38   0.00   0.00
31 2023-03-28 2023-03-27  24.51   0.00  75.49   0.00   0.00
32 2023-06-27 2023-06-26   3.55   0.00  80.37  16.08   0.00
33 2023-09-26 2023-09-25   0.00   0.00  81.30  18.70   0.00
34 2023-12-26 2023-12-22   0.00   0.00  79.00  21.00   0.00
35 2024-03-25 2024-03-22  11.35   0.00  79.94   8.72   0.00
36 2024-06-25 2024-06-24  40.27   0.00  59.73   0.00   0.00
37 2024-09-25 2024-09-24  52.47   0.00  47.53   0.00   0.00
38 2024-12-26 2024-12-24  74.56   0.00  24.39   1.05   0.00
39 2025-03-26 2025-03-25  87.71   0.00   1.10  11.19   0.00
40 2025-06-25 2025-06-24  90.83   0.00   0.00   9.17   0.00
41 2025-09-25 2025-09-24  65.37   0.00   0.00  34.63   0.00
42 2025-12-26 2025-12-24  54.36   0.00   0.00  45.64   0.00
43 2026-03-26 2026-03-25  54.45   0.00   0.00  45.55   0.00
44 2026-06-25 2026-06-24    NaN    NaN    NaN    NaN    NaN

### Second portfolio performance (details)

Note that the maximum drawdown of `Port2` is the same as for QQQ, with a rate of returns smaller than QQQ. The `Port2` diversification is not better than for QQQ. Overall `Port2` is less attractive than a buy-and-hold position in QQQ.

In [32]:
pr2.port_perf(fancy=True)

           RR     DD     RoMaD     DD_date    DD_start      DD_end  DD_days
symbol
Port2   14.95 -33.68  0.444019  2022-12-28  2021-11-19  2024-03-27      859
QQQ     19.98 -35.12  0.569017  2022-11-03  2021-12-27  2023-12-13      716
ONEQ    18.23 -35.23  0.517326  2022-12-28  2021-11-19  2024-01-29      801
SPY     14.89 -33.72  0.441738  2020-03-23  2020-02-19  2020-08-10      173
XLF     13.58 -42.86  0.316937  2020-03-23  2020-02-14  2021-01-06      327
PFG     14.01 -64.73  0.216397  2020-03-23  2018-01-26  2021-05-05     1195

### First portfolio rebalancing weights

As expected with very few exceptions `Port2` is dominated by a single asset, QQQ.

In our opinion `Port2` is an unattractive investment. If the rate of returns and the drawdown levels are acceptable for an investor, then she is better off by investing directly in a buy-and-hold strategy in QQQ.

In [33]:
pr2.get_weights(fancy=True)

        Droll       Dfix    PFG     QQQ    SPY    XLF  ONEQ
0  2015-06-25 2015-06-24   0.00    0.00  87.50  12.50   0.0
1  2015-09-25 2015-09-24   4.24   34.03   0.00  61.74   0.0
2  2015-12-28 2015-12-24  10.29   89.71   0.00   0.00   0.0
3  2016-03-28 2016-03-24   0.00  100.00   0.00   0.00   0.0
4  2016-06-27 2016-06-24   0.00  100.00   0.00   0.00   0.0
5  2016-09-27 2016-09-26   0.00  100.00   0.00   0.00   0.0
6  2016-12-27 2016-12-23   0.00  100.00   0.00   0.00   0.0
7  2017-03-28 2017-03-27   0.00  100.00   0.00   0.00   0.0
8  2017-06-27 2017-06-26   0.00  100.00   0.00   0.00   0.0
9  2017-09-26 2017-09-25   0.00  100.00   0.00   0.00   0.0
10 2017-12-26 2017-12-22   0.00  100.00   0.00   0.00   0.0
11 2018-03-26 2018-03-23   0.00  100.00   0.00   0.00   0.0
12 2018-06-26 2018-06-25   0.00  100.00   0.00   0.00   0.0
13 2018-09-25 2018-09-24   0.00  100.00   0.00   0.00   0.0
14 2018-12-26 2018-12-24   0.00   55.32  44.68   0.00   0.0
15 2019-03-26 2019-03-25   0.00   92.98   7.02   0.00   0.0
16 2019-06-25 2019-06-24   0.00  100.00   0.00   0.00   0.0
17 2019-09-25 2019-09-24   0.00  100.00   0.00   0.00   0.0
18 2019-12-26 2019-12-24   0.00  100.00   0.00   0.00   0.0
19 2020-03-26 2020-03-25   0.00  100.00   0.00   0.00   0.0
20 2020-06-25 2020-06-24   0.00  100.00   0.00   0.00   0.0
21 2020-09-25 2020-09-24   0.00  100.00   0.00   0.00   0.0
22 2020-12-28 2020-12-24   0.00  100.00   0.00   0.00   0.0
23 2021-03-26 2021-03-25   0.00  100.00   0.00   0.00   0.0
24 2021-06-25 2021-06-24   0.00  100.00   0.00   0.00   0.0
25 2021-09-27 2021-09-24   0.00  100.00   0.00   0.00   0.0
26 2021-12-28 2021-12-27   0.00  100.00   0.00   0.00   0.0
27 2022-03-28 2022-03-25   0.00  100.00   0.00   0.00   0.0
28 2022-06-27 2022-06-24   4.66   95.34   0.00   0.00   0.0
29 2022-09-27 2022-09-26   8.74   91.26   0.00   0.00   0.0
30 2022-12-27 2022-12-23  24.85   75.15   0.00   0.00   0.0
31 2023-03-28 2023-03-27  41.80   58.20   0.00   0.00   0.0
32 2023-06-27 2023-06-26  64.65   35.35   0.00   0.00   0.0
33 2023-09-26 2023-09-25  65.33   34.67   0.00   0.00   0.0
34 2023-12-26 2023-12-22  65.57   34.43   0.00   0.00   0.0
35 2024-03-25 2024-03-22  61.01   38.99   0.00   0.00   0.0
36 2024-06-25 2024-06-24  54.97   45.03   0.00   0.00   0.0
37 2024-09-25 2024-09-24  34.38    0.00  65.62   0.00   0.0
38 2024-12-26 2024-12-24  27.57    0.00  72.43   0.00   0.0
39 2025-03-26 2025-03-25  17.65    0.00  82.35   0.00   0.0
40 2025-06-25 2025-06-24   0.00   35.94   0.00  64.06   0.0
41 2025-09-25 2025-09-24   0.00   33.17   0.00  66.83   0.0
42 2025-12-26 2025-12-24   0.00   57.41   0.00  42.59   0.0
43 2026-03-26 2026-03-25   0.00   67.85   0.00  32.15   0.0
44 2026-06-25 2026-06-24    NaN     NaN    NaN    NaN   NaN