# Out-of-sample analysis - an example
### Mixture of CVaR's with Sharpe type of optimization

This is an illustration of *out-of-sample analysis* workflow. It is also known as *back testing* or *historical simulation*.

The example presented here is for a mCVaR (a mixture of 3 CVaR's) with Sharpe type of optimization (*i.e.* the portfolio that maximizes the mCVaR-Sharpe ratio).

Similar results can be obtained for any other implemented risk measure and type of optimization.

We start by importing the **azapy** and other useful packages.

In [49]:
import azapy as az

print(f"azapy version {az.version()} >= 1.2.0")

azapy version 1.2.6 >= 1.2.0

### Collect historical market data for a set of portfolio components.

- `symb` is the list of stock symbols (portfolio components).
- `sdate` and `edate` are the start and end dates of historical time-series.
- `mktdir` is the name of the directory used to save the market data.
    
> Note: if the flag `force=False` then a reading from `dir=mktdir` is attempted. If it fails, then the market data provider  servers will be accessed. The new data will be saved to the `dir=mktdir` (*for more information see the readMkT documentation* https://azapy.readthedocs.io/en/latest/).

In [50]:
symb = ['GLD', 'TLT', 'XLV', 'SPY', 'VHT']

sdate = "2012-01-01"
edate = "today"

mktdir = "../MkTdata"

mktdata = az.readMkT(symb, sdate=sdate, edate=edate, file_dir=mktdir)

read GLD data from file
read TLT data from file
read XLV data from file
read SPY data from file
read VHT data from file

Request between 2012-01-03 : 2026-05-05
                    GLD         TLT         XLV         SPY         VHT
source            yahoo       yahoo       yahoo       yahoo       yahoo
force             False       False       False       False       False
save               True        True        True        True        True
file_dir     ../MkTdata  ../MkTdata  ../MkTdata  ../MkTdata  ../MkTdata
file_format         csv         csv         csv         csv         csv
api_key            None        None        None        None        None
nrow               3605        3605        3605        3605        3605
sdate        2012-01-03  2012-01-03  2012-01-03  2012-01-03  2012-01-03
edate        2026-05-05  2026-05-05  2026-05-05  2026-05-05  2026-05-05
error                No          No          No          No          No
extraction time 0.29 s

### Set the mixture of CVaR's parameters

- `alpha` is the list of CVaR confidence levels,
- `coef` is the list of CVaR's weights (coefficients). 

Note: `len(coef)=len(alpha)`. All the coefficients must be `>0`.

In [51]:
alpha = [0.95, 0.90, 0.85]
coef = [0.2, 0.3, 0.5]

### Set the Port_CVaR class.

For a full list of available setting parameters see the documentation.

In [52]:
pr1 = az.Port_CVaR(mktdata, pname='CVaRPort')

### Set the model parameters 

> Note: This method must be called before any other. It will perform the main historical simulation.

For a full list of available setting parameters see the documentation.

In [53]:
port = pr1.set_model(alpha=alpha, coef=coef)

### View the portfolio time-series 

For reference EMA for 30 and 200 business days were added *(default behavior)*.

> Note the use of flag `fancy=True`. It designates the use of *plotly* package for interactive time-series. 

For a full list of available setting parameters see the documentation.

In [54]:
_ = pr1.port_view(fancy=True, title="Portfolio performance")

### View the portfolio and its components time-series (in a relative bases)

For a full list of available setting parameters see the documentation.

In [55]:
_ = pr1.port_view_all(fancy=True, title="Relative performance")

### Portfolio weights for each rebalancing period 

- `Droll` is the rolling date. The new positions are acquired at the end of trading day (theoretically at the closing price).
- `Dfix` is the fixing date relative to which the weights are computed. This is also the last closing prices included in the evaluation of the weights.
- `Dhist` this is the earliest date included in the calibration of weights. The hist data used in the calibration is between and including the `Dhist` and `Dfix`.

> Note the use of flag `fancy=True` - the weights are reported in percent with 2 decimals. 

For a full list of available setting parameters see the documentation.

In [56]:
pr1.get_weights(fancy=True)

        Droll       Dfix    GLD    TLT    XLV    SPY    VHT
0  2015-06-25 2015-06-24   0.00  10.29  89.71   0.00   0.00
1  2015-09-25 2015-09-24   0.00  16.05  55.59   0.00  28.36
2  2015-12-28 2015-12-24   0.00  29.29  34.11  36.60   0.00
3  2016-03-28 2016-03-24   0.00  40.57  46.32  13.12   0.00
4  2016-06-27 2016-06-24   0.00  40.23  39.51  20.25   0.00
5  2016-09-27 2016-09-26   0.00  46.49  37.11  16.40   0.00
6  2016-12-27 2016-12-23   0.00  35.10   0.00  64.90   0.00
7  2017-03-28 2017-03-27   0.00  33.23   0.00  66.77   0.00
8  2017-06-27 2017-06-26   0.00  33.14   0.00  66.86   0.00
9  2017-09-26 2017-09-25   0.00  33.08   0.00  66.92   0.00
10 2017-12-26 2017-12-22   0.00  32.16   0.00  67.84   0.00
11 2018-03-26 2018-03-23   0.00  29.37   0.00  70.63   0.00
12 2018-06-26 2018-06-25   0.00  30.14   0.00  69.86   0.00
13 2018-09-25 2018-09-24   0.00  28.62   0.00  71.38   0.00
14 2018-12-26 2018-12-24  31.11   0.00   4.73  64.16   0.00
15 2019-03-26 2019-03-25  37.31   0.00   0.00  62.69   0.00
16 2019-06-25 2019-06-24  33.63   0.00   0.00  66.37   0.00
17 2019-09-25 2019-09-24  36.97   0.00   0.00  63.03   0.00
18 2019-12-26 2019-12-24  45.75   5.29  12.80  36.16   0.00
19 2020-03-26 2020-03-25  37.94  30.58   7.64   1.16  22.69
20 2020-06-25 2020-06-24  37.63  32.12   4.67   0.00  25.57
21 2020-09-25 2020-09-24  40.03  29.67   0.00   2.90  27.40
22 2020-12-28 2020-12-24  40.54  26.14   0.00   1.65  31.67
23 2021-03-26 2021-03-25  44.62  16.64   0.00  18.38  20.37
24 2021-06-25 2021-06-24  39.11  16.65  20.72  23.52   0.00
25 2021-09-27 2021-09-24  48.72  11.29  11.19  28.80   0.00
26 2021-12-28 2021-12-27  15.68  36.99   0.00  47.33   0.00
27 2022-03-28 2022-03-25  47.51  12.04   0.00  40.45   0.00
28 2022-06-27 2022-06-24  52.78   0.00  47.22   0.00   0.00
29 2022-09-27 2022-09-26  27.86   0.00  72.14   0.00   0.00
30 2022-12-27 2022-12-23  21.62   0.00  78.38   0.00   0.00
31 2023-03-28 2023-03-27  24.51   0.00  75.49   0.00   0.00
32 2023-06-27 2023-06-26   3.55   0.00  80.37  16.08   0.00
33 2023-09-26 2023-09-25   0.00   0.00  81.30  18.70   0.00
34 2023-12-26 2023-12-22   0.00   0.00  79.00  21.00   0.00
35 2024-03-25 2024-03-22  11.35   0.00  79.94   8.72   0.00
36 2024-06-25 2024-06-24  40.27   0.00  59.73   0.00   0.00
37 2024-09-25 2024-09-24  52.47   0.00  47.53   0.00   0.00
38 2024-12-26 2024-12-24  74.56   0.00  24.39   1.05   0.00
39 2025-03-26 2025-03-25  87.71   0.00   1.10  11.19   0.00
40 2025-06-25 2025-06-24  90.83   0.00   0.00   9.17   0.00
41 2025-09-25 2025-09-24  65.37   0.00   0.00  34.63   0.00
42 2025-12-26 2025-12-24  54.36   0.00   0.00  45.64   0.00
43 2026-03-26 2026-03-25  54.45   0.00   0.00  45.55   0.00
44 2026-06-25 2026-06-24    NaN    NaN    NaN    NaN    NaN

### Portfolio performance

Reports the portfolio and its components performance for the duration of the investment.

- `RR` is the portfolio average annual rate of returns.
- `DD` is the maximum drawdown rate.
- `Beta` is the ratio `RR/DD`.
- `DD_date` is the date of maximum drawdown.
- `DD_start` is the date when the maximum drawdown event had started.
- `DD_end` is the date when the maximum drawdown event had ended. If it is `Nan`, then the drawdown is still in progress (`DD` and `DD_date` are only provisional).

> Note the use of flag `fancy=True` - the rates are reported in percent with 2 decimals.

In [57]:
pr1.port_perf(fancy=True)

             RR     DD     RoMaD     DD_date    DD_start      DD_end  DD_days
symbol
CVaRPort   9.57 -22.21  0.430984  2022-09-27  2021-11-12  2024-05-15      915
SPY       14.89 -33.72  0.441738  2020-03-23  2020-02-19  2020-08-10      173
XLV       12.28 -28.40  0.432176  2020-03-23  2020-01-22  2020-07-15      175
VHT       12.37 -28.85  0.428857  2020-03-23  2020-02-19  2020-06-08      110
GLD        7.14 -42.11  0.169582  2015-12-17  2012-10-04  2020-07-22     2848
TLT        0.41 -48.35  0.008530  2023-10-19  2020-08-04         NaN     2100

### Portfolio drawdowns 

Reports the largest drawdown events. The default is the first 5. 

> Note the use of flag fancy=True - the rates are reported in percent with 2 decimals.

For a full list of available setting parameters see the documentation.

In [58]:
pr1.port_drawdown(fancy=True)

       DD        Date       Start         End  NrDays
No
1  -22.21  2022-09-27  2021-11-12  2024-05-15     915
2  -17.97  2020-03-20  2020-02-21  2020-04-23      62
3  -16.71  2015-09-28  2015-08-05  2016-06-30     330
4  -16.21  2026-03-30  2026-01-29         NaN      96
5  -13.59  2018-12-24  2018-08-29  2019-01-31     155

### Portfolio annual returns 

Annual returns are per calendar year (1 Jan to 31 Dec). If the first or last years are incomplete, then the rates are reported per invested period in the respective years. 

> Note the use of flag fancy=True - the rates are reported in percent with 2 decimals.

In [59]:
pr1.port_annual_returns(fancy=True)

### Portfolio monthly returns

Same as above but per calendar month of each year. This are simple monthly rates. 

> Note the use of flag fancy=True - the rates are reported in percent with 2 decimals.

In [60]:
pr1.port_monthly_returns(fancy=True)

### Portfolio returns per rolling period 

Additional reference info is included in the report. 

- `Droll` is the rolling date. Identifies the start of the rolling period, (Droll, next Droll].
- `Dfix` is the fixing date.
- `RR` simple rate of return per rolling period.
- portfolio weights for each rolling period.

> Note the use of flag fancy=True - the rates are reported in percent with 2 decimals.

In [61]:
pr1.port_period_returns(fancy=True)

        Droll       Dfix     RR    GLD    TLT    XLV    SPY    VHT
0  2015-06-25 2015-06-24 -10.44   0.00  10.29  89.71   0.00   0.00
1  2015-09-25 2015-09-24   3.76   0.00  16.05  55.59   0.00  28.36
2  2015-12-28 2015-12-24   1.89   0.00  29.29  34.11  36.60   0.00
3  2016-03-28 2016-03-24   4.02   0.00  40.57  46.32  13.12   0.00
4  2016-06-27 2016-06-24   4.66   0.00  40.23  39.51  20.25   0.00
5  2016-09-27 2016-09-26  -7.00   0.00  46.49  37.11  16.40   0.00
6  2016-12-27 2016-12-23   3.54   0.00  35.10   0.00  64.90   0.00
7  2017-03-28 2017-03-27   4.12   0.00  33.23   0.00  66.77   0.00
8  2017-06-27 2017-06-26   1.49   0.00  33.14   0.00  66.86   0.00
9  2017-09-26 2017-09-25   5.83   0.00  33.08   0.00  66.92   0.00
10 2017-12-26 2017-12-22  -1.42   0.00  32.16   0.00  67.84   0.00
11 2018-03-26 2018-03-23   4.37   0.00  29.37   0.00  70.63   0.00
12 2018-06-26 2018-06-25   2.82   0.00  30.14   0.00  69.86   0.00
13 2018-09-25 2018-09-24  -9.94   0.00  28.62   0.00  71.38   0.00
14 2018-12-26 2018-12-24  15.51  31.11   0.00   4.73  64.16   0.00
15 2019-03-26 2019-03-25   2.58  37.31   0.00   0.00  62.69   0.00
16 2019-06-25 2019-06-24   3.03  33.63   0.00   0.00  66.37   0.00
17 2019-09-25 2019-09-24   6.18  36.97   0.00   0.00  63.03   0.00
18 2019-12-26 2019-12-24  -3.27  45.75   5.29  12.80  36.16   0.00
19 2020-03-26 2020-03-25  11.02  37.94  30.58   7.64   1.16  22.69
20 2020-06-25 2020-06-24   1.87  37.63  32.12   4.67   0.00  25.57
21 2020-09-25 2020-09-24   2.48  40.03  29.67   0.00   2.90  27.40
22 2020-12-28 2020-12-24  -5.78  40.54  26.14   0.00   1.65  31.67
23 2021-03-26 2021-03-25   6.01  44.62  16.64   0.00  18.38  20.37
24 2021-06-25 2021-06-24   1.17  39.11  16.65  20.72  23.52   0.00
25 2021-09-27 2021-09-24   4.45  48.72  11.29  11.19  28.80   0.00
26 2021-12-28 2021-12-27  -5.54  15.68  36.99   0.00  47.33   0.00
27 2022-03-28 2022-03-25 -10.14  47.51  12.04   0.00  40.45   0.00
28 2022-06-27 2022-06-24  -7.94  52.78   0.00  47.22   0.00   0.00
29 2022-09-27 2022-09-26  11.75  27.86   0.00  72.14   0.00   0.00
30 2022-12-27 2022-12-23  -2.65  21.62   0.00  78.38   0.00   0.00
31 2023-03-28 2023-03-27   1.52  24.51   0.00  75.49   0.00   0.00
32 2023-06-27 2023-06-26  -0.52   3.55   0.00  80.37  16.08   0.00
33 2023-09-26 2023-09-25   5.11   0.00   0.00  81.30  18.70   0.00
34 2023-12-26 2023-12-22   9.38   0.00   0.00  79.00  21.00   0.00
35 2024-03-25 2024-03-22   1.99  11.35   0.00  79.94   8.72   0.00
36 2024-06-25 2024-06-24   8.24  40.27   0.00  59.73   0.00   0.00
37 2024-09-25 2024-09-24  -4.50  52.47   0.00  47.53   0.00   0.00
38 2024-12-26 2024-12-24  13.03  74.56   0.00  24.39   1.05   0.00
39 2025-03-26 2025-03-25   9.10  87.71   0.00   1.10  11.19   0.00
40 2025-06-25 2025-06-24  12.65  90.83   0.00   0.00   9.17   0.00
41 2025-09-25 2025-09-24  15.16  65.37   0.00   0.00  34.63   0.00
42 2025-12-26 2025-12-24  -4.53  54.36   0.00   0.00  45.64   0.00
43 2026-03-26 2026-03-25   4.48  54.45   0.00   0.00  45.55   0.00

### Number of shares invested at each rebalancing period

In [62]:
pr1.get_nshares()

            GLD  SPY  TLT  VHT   XLV  _CASH_
Droll
2015-06-25    0    0   88    0  1185       0
2015-09-25    0    0  118  199   727       0
2015-12-28    0  171  231    0   452       0
2016-03-28    0   62  299    0   657       0
2016-06-27    0   99  295    0   567       0
2016-09-27    0   79  351    0   533       0
2016-12-27    0  277  286    0     0       0
2017-03-28    0  286  274    0     0       0
2017-06-27    0  286  269    0     0       0
2017-09-26    0  287  278    0     0       0
2017-12-26    0  284  289    0     0       0
2018-03-26    0  302  270    0     0       0
2018-06-26    0  292  283    0     0       0
2018-09-25    0  290  290    0     0       0
2018-12-26  278  293    0    0    63       0
2019-03-26  357  268    0    0     0       0
2019-06-25  316  285    0    0     0       0
2019-09-25  334  279    0    0     0       0
2019-12-26  448  156   54    0   172       0
2020-03-26  333    6  250  197   125       0
2020-06-25  328    0  285  196    69       0
2020-09-25  343   13  270  211     0       0
2020-12-28  354    7  256  220     0       0
2021-03-26  402   69  177  132     0       0
2021-06-25  362   85  178    0   254       0
2021-09-27  465  101  120    0   132       0
2021-12-28  152  162  407    0     0       0
2022-03-28  403  138  145    0     0       0
2022-06-27  433    0    0    0   509       0
2022-09-27  235    0    0    0   756       0
2022-12-27  185    0    0    0   823       0
2023-03-28  187    0    0    0   820       0
2023-06-27   28   53    0    0   866       0
2023-09-26    0   61    0    0   872       0
2023-12-26    0   66    0    0   871       0
2024-03-25   91   27    0    0   885       0
2024-06-25  307    0    0    0   669       0
2024-09-25  381    0    0    0   551       0
2024-12-26  527    3    0    0   299       0
2025-03-26  601   37    0    0    15       0
2025-06-25  622   32    0    0     0       0
2025-09-25  447  123    0    0     0       0
2025-12-26  358  179    0    0     0       0
2026-03-26  337  179    0    0     0       0

### Additional accounting information

Additional accounting information per rebalancing period.

- `Droll` rolling date. It identifies the rebalancing period.
- Invested number of shares per portfolio component
- `cash_invst` is the dollar value of the invested shares at the beginning of rebalancing period (using closing prices in the `Droll` date).
- `cash_roll` amount of cash rolled to next period. The source of this cash is twofold. First due to rounding to an integer number of shares and second due to price slippage between the weights computation time, `Dfix` date, and the execution (buy/sale) of the portfolio positions, `Droll` date. It can be positive or negative. In both cases it is a small value relative to the invested capital. It is the investor obligation to make the shortfall until next rolling date. 
- `cash_divd` is the amount of cash collected during the rebalancing period. It will be part of the investor capital in the next period.

In [63]:
pr1.get_account(fancy=True)

,GLD,SPY,TLT,VHT,XLV,_CASH_,cash_invst,cash_roll,cash_divd
Droll,,,,,,,,,
2015-06-25,0.0,0.0,88.0,0.0,1185.0,0.0,100434.02,-434.02,0.00
2015-09-25,0.0,0.0,118.0,199.0,727.0,0.0,87715.10,2177.83,378.63
2015-12-28,0.0,171.0,231.0,0.0,452.0,0.0,95910.52,33.62,437.02
2016-03-28,0.0,62.0,299.0,0.0,657.0,0.0,95534.57,-9.87,399.63
2016-06-27,0.0,99.0,295.0,0.0,567.0,0.0,99587.01,-191.81,492.38
2016-09-27,0.0,79.0,351.0,0.0,533.0,0.0,104500.14,-681.85,491.58
2016-12-27,0.0,277.0,286.0,0.0,0.0,0.0,96330.41,-102.21,635.75
2017-03-28,0.0,286.0,274.0,0.0,0.0,0.0,100351.40,-345.51,427.14
2017-06-27,0.0,286.0,269.0,0.0,0.0,0.0,103153.79,839.08,550.14
2017-09-26,0.0,287.0,278.0,0.0,0.0,0.0,106725.24,14.88,565.72
2017-12-26,0.0,284.0,289.0,0.0,0.0,0.0,112047.42,114.55,674.63
2018-03-26,0.0,302.0,270.0,0.0,0.0,0.0,112384.92,-1928.63,454.31
2018-06-26,0.0,292.0,283.0,0.0,0.0,0.0,113541.71,-192.14,593.10
2018-09-25,0.0,290.0,290.0,0.0,0.0,0.0,118154.70,189.28,616.68
2018-12-26,278.0,293.0,0.0,0.0,63.0,0.0,110702.08,-3584.00,730.80
2019-03-26,357.0,268.0,0.0,0.0,0.0,0.0,119715.26,-247.98,382.75
2019-06-25,316.0,285.0,0.0,0.0,0.0,0.0,125273.80,695.08,383.78
2019-09-25,334.0,279.0,0.0,0.0,0.0,0.0,130407.20,322.30,394.44
2019-12-26,448.0,156.0,54.0,0.0,172.0,0.0,139272.58,-857.08,438.03
2020-03-26,333.0,6.0,250.0,197.0,125.0,0.0,136453.53,-3728.30,425.03
2020-06-25,328.0,0.0,285.0,196.0,69.0,0.0,145158.29,-683.03,376.25
2020-09-25,343.0,13.0,270.0,211.0,0.0,0.0,150897.84,-670.35,313.54
2020-12-28,354.0,7.0,256.0,220.0,0.0,0.0,153820.69,225.59,386.19
2021-03-26,402.0,69.0,177.0,132.0,0.0,0.0,146866.20,-989.30,237.73
2021-06-25,362.0,85.0,178.0,0.0,254.0,0.0,153773.01,-312.95,291.11
2021-09-27,465.0,101.0,120.0,0.0,132.0,0.0,155536.84,451.05,339.50
2021-12-28,152.0,162.0,407.0,0.0,0.0,0.0,163240.25,441.26,321.39
2022-03-28,403.0,138.0,145.0,0.0,0.0,0.0,153891.96,813.33,377.17
2022-06-27,433.0,0.0,0.0,0.0,509.0,0.0,139573.81,-177.00,306.37
2022-09-27,235.0,0.0,0.0,0.0,756.0,0.0,127231.54,151.54,257.55
2022-12-27,185.0,0.0,0.0,0.0,823.0,0.0,142926.20,-89.87,420.34
2023-03-28,187.0,0.0,0.0,0.0,820.0,0.0,138484.28,326.84,402.45
2023-06-27,28.0,53.0,0.0,0.0,866.0,0.0,141495.03,-116.72,444.44
2023-09-26,0.0,61.0,0.0,0.0,872.0,0.0,139120.68,1185.12,551.54
2023-12-26,0.0,66.0,0.0,0.0,871.0,0.0,149256.63,-420.09,637.72
2024-03-25,91.0,27.0,0.0,0.0,885.0,0.0,160861.29,88.30,560.80
2024-06-25,307.0,0.0,0.0,0.0,669.0,0.0,163965.39,680.43,554.60
2024-09-25,381.0,0.0,0.0,0.0,551.0,0.0,177700.22,888.04,386.01
2024-12-26,527.0,3.0,0.0,0.0,299.0,0.0,171642.32,-882.28,342.72
2025-03-26,601.0,37.0,0.0,0.0,15.0,0.0,190431.17,476.09,174.02
2025-06-25,622.0,32.0,0.0,0.0,0.0,0.0,210456.48,-854.73,74.61
2025-09-25,447.0,123.0,0.0,0.0,0.0,0.0,235043.40,-347.43,58.59
2025-12-26,358.0,179.0,0.0,0.0,0.0,0.0,272758.41,-1669.79,245.14
2026-03-26,337.0,179.0,0.0,0.0,0.0,0.0,250486.80,7065.31,321.66