# Out-of-sample analysis - an example
### Mixture of CVaR's with Sharpe type of optimization

This is an illustration of *out-of-sample analysis* workflow. It is also known as *back testing* or *historical simulation*.

The example presented here is for a mCVaR (a mixture of 3 CVaR's) with Sharpe type of optimization (*i.e.* the portfolio that maximizes the mCVaR-Sharpe ratio).

Similar results can be obtained for any other implemented risk measure and type of optimization.

We start by importing the **azapy** and other useful packages.

In [1]:
import azapy as az

print(f"azapy version {az.version()} >= 1.2.0")

azapy version 1.2.5 >= 1.2.0

### Collect historical market data for a set of portfolio components.

- `symb` is the list of stock symbols (portfolio components).
- `sdate` and `edate` are the start and end dates of historical time-series.
- `mktdir` is the name of the directory used to save the market data.
    
> Note: if the flag `force=False` then a reading from `dir=mktdir` is attempted. If it fails, then the market data provider  servers will be accessed. The new data will be saved to the `dir=mktdir` (*for more information see the readMkT documentation* https://azapy.readthedocs.io/en/latest/).

In [2]:
symb = ['GLD', 'TLT', 'XLV', 'VGT', 'VHT']

sdate = "2012-01-01"
edate = "2021-07-27"

mktdir = "../MkTdata"

mktdata = az.readMkT(symb, sdate=sdate, edate=edate, file_dir=mktdir)

read GLD data from file
read TLT data from file
read XLV data from file
read VGT data from file
read VHT data from file

Request between 2012-01-03 : 2021-07-27
                    GLD         TLT         XLV         VGT         VHT
source            yahoo       yahoo       yahoo       yahoo       yahoo
force             False       False       False       False       False
save               True        True        True        True        True
file_dir     ../MkTdata  ../MkTdata  ../MkTdata  ../MkTdata  ../MkTdata
file_format         csv         csv         csv         csv         csv
api_key            None        None        None        None        None
nrow               2407        2407        2407        2407        2407
sdate        2012-01-03  2012-01-03  2012-01-03  2012-01-03  2012-01-03
edate        2021-07-27  2021-07-27  2021-07-27  2021-07-27  2021-07-27
error                No          No          No          No          No
extraction time 0.173 s

### Set the mixture of CVaR's parameters

- `alpha` is the list of CVaR confidence levels,
- `coef` is the list of CVaR's weights (coefficients). 

Note: `len(coef)=len(alpha)`. All the coefficients must be `>0`.

In [3]:
alpha = [0.95, 0.90, 0.85]
coef = [0.2, 0.3, 0.5]

### Set the Port_CVaR class.

For a full list of available setting parameters see the documentation.

In [4]:
pr1 = az.Port_CVaR(mktdata, pname='CVaRPort')

### Set the model parameters 

> Note: This method must be called before any other. It will perform the main historical simulation.

For a full list of available setting parameters see the documentation.

In [5]:
port = pr1.set_model(alpha=alpha, coef=coef)

### View the portfolio time-series 

For reference EMA for 30 and 200 business days were added *(default behavior)*.

> Note the use of flag `fancy=True`. It designates the use of *plotly* package for interactive time-series. 

For a full list of available setting parameters see the documentation.

In [6]:
_ = pr1.port_view(fancy=True, title="Portfolio performance")

### View the portfolio and its components time-series (in a relative bases)

For a full list of available setting parameters see the documentation.

In [7]:
_ = pr1.port_view_all(fancy=True, title="Relative performance")

### Portfolio weights for each rebalancing period 

- `Droll` is the rolling date. The new positions are acquired at the end of trading day (theoretically at the closing price).
- `Dfix` is the fixing date relative to which the weights are computed. This is also the last closing prices included in the evaluation of the weights.
- `Dhist` this is the earliest date included in the calibration of weights. The hist data used in the calibration is between and including the `Dhist` and `Dfix`.

> Note the use of flag `fancy=True` - the weights are reported in percent with 2 decimals. 

For a full list of available setting parameters see the documentation.

In [8]:
pr1.get_weights(fancy=True)

        Droll       Dfix    GLD    TLT    XLV    VGT    VHT
0  2015-06-25 2015-06-24   0.00  10.29  89.71   0.00   0.00
1  2015-09-25 2015-09-24   0.00  16.05  55.59   0.00  28.36
2  2015-12-28 2015-12-24   0.00  28.47  32.76  38.77   0.00
3  2016-03-28 2016-03-24   0.00  40.40  38.86  20.74   0.00
4  2016-06-27 2016-06-24   0.00  40.64  34.47  24.89   0.00
5  2016-09-27 2016-09-26   0.00  46.09  32.28  21.63   0.00
6  2016-12-27 2016-12-23   0.00  38.92   0.00  61.08   0.00
7  2017-03-28 2017-03-27   0.00  37.01   0.00  62.99   0.00
8  2017-06-27 2017-06-26   0.00  36.09   0.00  63.91   0.00
9  2017-09-26 2017-09-25   0.00  36.03   0.00  63.97   0.00
10 2017-12-26 2017-12-22   0.00  34.61   0.00  65.39   0.00
11 2018-03-26 2018-03-23   0.00  32.25   0.00  67.75   0.00
12 2018-06-26 2018-06-25   0.00  33.14   0.00  66.86   0.00
13 2018-09-25 2018-09-24   0.31  31.77   0.00  67.92   0.00
14 2018-12-26 2018-12-24  32.84   0.00   2.95  64.20   0.00
15 2019-03-26 2019-03-25  39.39   0.00   0.00  60.61   0.00
16 2019-06-25 2019-06-24  36.15   0.00   0.00  63.85   0.00
17 2019-09-25 2019-09-24  38.33   0.00   0.00  61.67   0.00
18 2019-12-26 2019-12-24  51.84   0.00  10.70  37.45   0.00
19 2020-03-26 2020-03-25  42.81  24.80  15.55  16.84   0.00
20 2020-06-25 2020-06-24  41.67  26.81  15.96  15.56   0.00
21 2020-09-25 2020-09-24  43.98  24.42  14.00  17.60   0.00
22 2020-12-28 2020-12-24  45.35  21.19  11.75  21.70   0.00
23 2021-03-26 2021-03-25  51.96   9.76   5.32  32.96   0.00
24 2021-06-25 2021-06-24  48.59   7.54  17.75  26.12   0.00
25 2021-09-27 2021-09-24    NaN    NaN    NaN    NaN    NaN

### Portfolio performance

Reports the portfolio and its components performance for the duration of the investment.

- `RR` is the portfolio average annual rate of returns.
- `DD` is the maximum drawdown rate.
- `Beta` is the ratio `RR/DD`.
- `DD_date` is the date of maximum drawdown.
- `DD_start` is the date when the maximum drawdown event had started.
- `DD_end` is the date when the maximum drawdown event had ended. If it is `Nan`, then the drawdown is still in progress (`DD` and `DD_date` are only provisional).

> Note the use of flag `fancy=True` - the rates are reported in percent with 2 decimals.

In [9]:
pr1.port_perf(fancy=True)

             RR     DD     RoMaD     DD_date    DD_start      DD_end  DD_days
symbol
CVaRPort  12.84 -18.53  0.692856  2020-03-20  2020-02-19  2020-04-24       65
VGT       23.10 -31.84  0.725512  2020-03-23  2020-02-19  2020-06-09      111
VHT       17.41 -28.85  0.603515  2020-03-23  2020-02-19  2020-06-08      110
XLV       16.74 -28.40  0.589180  2020-03-23  2020-01-22  2020-07-15      175
TLT        4.89 -21.34  0.229103  2021-03-18  2020-08-04         NaN      357
GLD        0.81 -42.11  0.019280  2015-12-17  2012-10-04  2020-07-22     2848

### Portfolio drawdowns 

Reports the largest drawdown events. The default is the first 5. 

> Note the use of flag fancy=True - the rates are reported in percent with 2 decimals.

For a full list of available setting parameters see the documentation.

In [10]:
pr1.port_drawdown(fancy=True)

       DD        Date       Start         End  NrDays
No
1  -18.53  2020-03-20  2020-02-19  2020-04-24      65
2  -16.71  2015-09-28  2015-08-05  2016-07-06     336
3  -15.55  2018-12-24  2018-08-31  2019-02-05     158
4  -10.73  2021-03-08  2020-08-06  2021-06-10     308
5   -9.03  2016-12-01  2016-09-28  2017-04-24     208

### Portfolio annual returns 

Annual returns are per calendar year (1 Jan to 31 Dec). If the first or last years are incomplete, then the rates are reported per invested period in the respective years. 

> Note the use of flag fancy=True - the rates are reported in percent with 2 decimals.

In [11]:
pr1.port_annual_returns(fancy=True)

### Portfolio monthly returns

Same as above but per calendar month of each year. This are simple monthly rates. 

> Note the use of flag fancy=True - the rates are reported in percent with 2 decimals.

In [12]:
pr1.port_monthly_returns(fancy=True)

### Portfolio returns per rolling period 

Additional reference info is included in the report. 

- `Droll` is the rolling date. Identifies the start of the rolling period, (Droll, next Droll].
- `Dfix` is the fixing date.
- `RR` simple rate of return per rolling period.
- portfolio weights for each rolling period.

> Note the use of flag fancy=True - the rates are reported in percent with 2 decimals.

In [13]:
pr1.port_period_returns(fancy=True)

        Droll       Dfix     RR    GLD    TLT    XLV    VGT    VHT
0  2015-06-25 2015-06-24 -10.44   0.00  10.29  89.71   0.00   0.00
1  2015-09-25 2015-09-24   3.76   0.00  16.05  55.59   0.00  28.36
2  2015-12-28 2015-12-24   1.38   0.00  28.47  32.76  38.77   0.00
3  2016-03-28 2016-03-24   3.11   0.00  40.40  38.86  20.74   0.00
4  2016-06-27 2016-06-24   6.72   0.00  40.64  34.47  24.89   0.00
5  2016-09-27 2016-09-26  -6.34   0.00  46.09  32.28  21.63   0.00
6  2016-12-27 2016-12-23   6.41   0.00  38.92   0.00  61.08   0.00
7  2017-03-28 2017-03-27   5.60   0.00  37.01   0.00  62.99   0.00
8  2017-06-27 2017-06-26   1.63   0.00  36.09   0.00  63.91   0.00
9  2017-09-26 2017-09-25   8.56   0.00  36.03   0.00  63.97   0.00
10 2017-12-26 2017-12-22   2.42   0.00  34.61   0.00  65.39   0.00
11 2018-03-26 2018-03-23   6.48   0.00  32.25   0.00  67.75   0.00
12 2018-06-26 2018-06-25   3.96   0.00  33.14   0.00  66.86   0.00
13 2018-09-25 2018-09-24 -11.45   0.31  31.77   0.00  67.92   0.00
14 2018-12-26 2018-12-24  20.57  32.84   0.00   2.95  64.20   0.00
15 2019-03-26 2019-03-25   2.77  39.39   0.00   0.00  60.61   0.00
16 2019-06-25 2019-06-24   3.79  36.15   0.00   0.00  63.85   0.00
17 2019-09-25 2019-09-24   9.60  38.33   0.00   0.00  61.67   0.00
18 2019-12-26 2019-12-24  -0.96  51.84   0.00  10.70  37.45   0.00
19 2020-03-26 2020-03-25  12.89  42.81  24.80  15.55  16.84   0.00
20 2020-06-25 2020-06-24   3.03  41.67  26.81  15.96  15.56   0.00
21 2020-09-25 2020-09-24   3.66  43.98  24.42  14.00  17.60   0.00
22 2020-12-28 2020-12-24  -5.99  45.35  21.19  11.75  21.70   0.00
23 2021-03-26 2021-03-25   6.61  51.96   9.76   5.32  32.96   0.00
24 2021-06-25 2021-06-24   2.29  48.59   7.54  17.75  26.12   0.00

### Number of shares invested at each rebalancing period

In [14]:
pr1.get_nshares()

            GLD  TLT  VGT  VHT   XLV  _CASH_
Droll
2015-06-25    0   88    0    0  1185       0
2015-09-25    0  118    0  199   727       0
2015-12-28    0  224  340    0   434       0
2016-03-28    0  297  184    0   548       0
2016-06-27    0  293  233    0   488       0
2016-09-27    0  351  191    0   468       0
2016-12-27    0  320  482    0     0       0
2017-03-28    0  317  488    0     0       0
2017-06-27    0  308  484    0     0       0
2017-09-26    0  322  488    0     0       0
2017-12-26    0  337  477    0     0       0
2018-03-26    0  334  501    0     0       0
2018-06-26    0  354  475    0     0       0
2018-09-25    4  374  463    0     0       0
2018-12-26  334    0  506    0    45       0
2019-03-26  448    0  435    0     0       0
2019-06-25  406    0  454    0     0       0
2019-09-25  418    0  454    0     0       0
2019-12-26  630    0  264    0   178       0
2020-03-26  477  257  139    0   322       0
2020-06-25  470  308  107    0   305       0
2020-09-25  493  291  117    0   271       0
2020-12-28  523  274  125    0   214       0
2021-03-26  618  137  181    0    89       0
2021-06-25  595  107  135    0   288       0

### Additional accounting information

Additional accounting information per rebalancing period.

- `Droll` rolling date. It identifies the rebalancing period.
- Invested number of shares per portfolio component
- `cash_invst` is the dollar value of the invested shares at the beginning of rebalancing period (using closing prices in the `Droll` date).
- `cash_roll` amount of cash rolled to next period. The source of this cash is twofold. First due to rounding to an integer number of shares and second due to price slippage between the weights computation time, `Dfix` date, and the execution (buy/sale) of the portfolio positions, `Droll` date. It can be positive or negative. In both cases it is a small value relative to the invested capital. It is the investor obligation to make the shortfall until next rolling date. 
- `cash_divd` is the amount of cash collected during the rebalancing period. It will be part of the investor capital in the next period.

In [15]:
pr1.get_account(fancy=True)

            GLD  TLT  VGT  VHT   XLV  _CASH_  cash_invst  cash_roll  cash_divd
Droll
2015-06-25    0   88    0    0  1185     0.0   100434.02    -434.02       0.00
2015-09-25    0  118    0  199   727     0.0    87715.10    2177.83     378.63
2015-12-28    0  224  340    0   434     0.0    95824.90     119.24     437.02
2016-03-28    0  297  184    0   548     0.0    95046.67      40.18     350.77
2016-06-27    0  293  233    0   488     0.0    97898.27     161.89     457.29
2016-09-27    0  351  191    0   468     0.0   105665.79    -931.27     454.78
2016-12-27    0  320  482    0     0     0.0    97321.18    -139.95     593.64
2017-03-28    0  317  488    0     0     0.0   104223.90    -256.68     332.73
2017-06-27    0  308  484    0     0     0.0   107873.04    1698.89     245.04
2017-09-26    0  322  488    0     0     0.0   113738.56    -233.65     439.82
2017-12-26    0  337  477    0     0     0.0   120963.04     456.27     750.03
2018-03-26    0  334  501    0     0     0.0   127673.17   -3038.54     346.78
2018-06-26    0  354  475    0     0     0.0   129525.13    -443.96     268.20
2018-09-25    4  374  463    0     0     0.0   137438.35      15.39     828.23
2018-12-26  334    0  506    0    45     0.0   126821.30   -4731.14     702.57
2019-03-26  448    0  435    0     0     0.0   142268.80    -348.52     317.43
2019-06-25  406    0  454    0     0     0.0   148699.28    1622.53     277.53
2019-09-25  418    0  454    0     0     0.0   157798.40     -79.43       0.00
2019-12-26  630    0  264    0   178     0.0   172890.10   -1219.08     674.19
2020-03-26  477  257  139    0   322     0.0   173276.23   -4658.32     408.57
2020-06-25  470  308  107    0   305     0.0   187931.11    -922.27     401.32
2020-09-25  493  291  117    0   271     0.0   197823.88   -1302.61     377.16
2020-12-28  523  274  125    0   214     0.0   203347.47      28.07     399.99
2021-03-26  618  137  181    0    89     0.0   194125.31   -1800.70     259.15
2021-06-25  595  107  135    0   288     0.0   203579.46    -413.54     229.29