# Universal portfolio - Cover 1996

This is an example of how to evaluate a Universal portfolio. For more details see the library documentation 
https://azapy.readthedocs.io/en/latest/.

We start by importing **azapy** and other useful packages
(**azapy** version must be 1.2.1 or greater).

In [1]:
import azapy as az

print(f"azapy version {az.version()} >= 1.2.0")

azapy version 1.2.5 >= 1.2.0

### Collect historical market data

- `symb` is the list of stock symbols (portfolio components).
- `sdate` and `edate` are the start and end dates of historical time-series.
- `mktdir` is the name of the directory used as a buffer for market data collected from the data provider (in this case _alphavantage_).
    
> Note: if the flag `force=False` then a reading from `dir=mktdir` is attempted. If it fails, then the data provider servers will be accessed. The new data will be saved to the `dir=mktdir`. For more information see the readMkT documentation https://azapy.readthedocs.io/en/latest/.

In [2]:
mktdir = '../MkTdata'
sdate = '2012-01-01'
edate = '2023-06-30'
symb = ['VGT', 'SPY', 'XLV', 'GLD', 'ONEQ']

mktdata = az.readMkT(symb, sdate=sdate, edate=edate, file_dir=mktdir)

read VGT data from file
read SPY data from file
read XLV data from file
read GLD data from file
read ONEQ data from file

Request between 2012-01-03 : 2023-06-30
                    VGT         SPY         XLV         GLD        ONEQ
source            yahoo       yahoo       yahoo       yahoo       yahoo
force             False       False       False       False       False
save               True        True        True        True        True
file_dir     ../MkTdata  ../MkTdata  ../MkTdata  ../MkTdata  ../MkTdata
file_format         csv         csv         csv         csv         csv
api_key            None        None        None        None        None
nrow               2892        2892        2892        2892        2892
sdate        2012-01-03  2012-01-03  2012-01-03  2012-01-03  2012-01-03
edate        2023-06-30  2023-06-30  2023-06-30  2023-06-30  2023-06-30
error                No          No          No          No          No
extraction time 0.191 s

### Setup the Universal portfolio

First line is the constructor
Second line sets the model and execute the core computations. It is a Monte Carlo based evaluation.

- `mc_paths` - are the number of simulations per batch (must be >= 1)
- `nr_batches` - are the number of batches (must be >= 1). Note that the computation is multithreaded with one batch per thread.
- `variance_reduction = True` - default value (the MC will use the antithetic variance reduce implied by the permutations of the basket components)
- `alpha_dirichlet = None` - default value. In this case a uniform random generator of vectors in the M-simplex is used. This is equivalent to a Flat Dirichlet random generator (all alpha set to 1).

>Note the the total number of MC simulations is `mc_paths * nr_batches * M!` where `M` is the number of portfolio components and `M!` its factorial.

In [3]:
p4 = az.Port_Universal(mktdata, pname='UnivPort')    
port4 = p4.set_model(mc_paths=100, nr_batches=20, verbose=True)

nr simulations: 240000
simulation time: 0.445903

### Historical portfolio weights

>Note: if `_CASH_` is not an explicit component of the portfolio (it is not present in the `makdata`), then its weight is
set to `0`.
A `_CASH_` asset can be added to the `mktdata` by using the helper function `azapy.add_cash_security(mktdata)`.

In [4]:
p4.get_weights()

,Droll,Dfix,GLD,ONEQ,SPY,VGT,XLV,_CASH_
0,2015-06-25,2015-06-24,0.200000,0.200000,0.200000,0.200000,0.200000,0
1,2015-09-25,2015-09-24,0.201676,0.199706,0.199552,0.199842,0.199224,0
2,2015-12-28,2015-12-24,0.198138,0.200509,0.200480,0.201178,0.199695,0
3,2016-03-28,2016-03-24,0.202431,0.198820,0.200343,0.200796,0.197610,0
4,2016-06-27,2016-06-24,0.204538,0.198037,0.199908,0.199482,0.198035,0
5,2016-09-27,2016-09-26,0.202581,0.199305,0.199469,0.201428,0.197216,0
6,2016-12-27,2016-12-23,0.197670,0.201062,0.201748,0.203129,0.196390,0
7,2017-03-28,2017-03-27,0.198569,0.200875,0.200573,0.203626,0.196357,0
8,2017-06-27,2017-06-26,0.196613,0.201420,0.200346,0.204361,0.197260,0
9,2017-09-26,2017-09-25,0.197298,0.201138,0.200289,0.204468,0.196808,0
10,2017-12-26,2017-12-22,0.194613,0.202249,0.200923,0.206507,0.195707,0
11,2018-03-26,2018-03-23,0.196292,0.202345,0.199829,0.207006,0.194528,0
12,2018-06-26,2018-06-25,0.193126,0.203520,0.200194,0.208125,0.195035,0
13,2018-09-25,2018-09-24,0.189605,0.203362,0.200526,0.209731,0.196776,0
14,2018-12-26,2018-12-24,0.196923,0.200539,0.198992,0.206439,0.197106,0
15,2019-03-26,2019-03-25,0.193207,0.202093,0.199489,0.209510,0.195700,0
16,2019-06-25,2019-06-24,0.193619,0.202008,0.199469,0.209931,0.194974,0
17,2019-09-25,2019-09-24,0.195527,0.201500,0.199339,0.209894,0.193739,0
18,2019-12-26,2019-12-24,0.192103,0.202295,0.199166,0.211454,0.194982,0
19,2020-03-26,2020-03-25,0.199579,0.201029,0.195854,0.210761,0.192777,0
20,2020-06-25,2020-06-24,0.195676,0.203628,0.195641,0.213284,0.191772,0
21,2020-09-25,2020-09-24,0.195341,0.203976,0.195616,0.214083,0.190983,0
22,2020-12-28,2020-12-24,0.191806,0.206039,0.195969,0.215980,0.190207,0
23,2021-03-26,2021-03-25,0.189219,0.206315,0.197767,0.215555,0.191143,0
24,2021-06-25,2021-06-24,0.187407,0.206902,0.197804,0.216725,0.191162,0
25,2021-09-27,2021-09-24,0.185702,0.207014,0.197898,0.217820,0.191568,0
26,2021-12-28,2021-12-27,0.184749,0.206607,0.198083,0.219051,0.191509,0
27,2022-03-28,2022-03-25,0.188507,0.204589,0.198108,0.216638,0.192158,0
28,2022-06-27,2022-06-24,0.190367,0.202479,0.197683,0.214687,0.194785,0
29,2022-09-27,2022-09-26,0.189170,0.202803,0.198089,0.214525,0.195413,0
30,2022-12-27,2022-12-23,0.190712,0.200319,0.198238,0.213121,0.197610,0
31,2023-03-28,2023-03-27,0.191124,0.201880,0.197213,0.216095,0.193689,0
32,2023-06-27,2023-06-26,0.188293,0.203561,0.197491,0.218453,0.192203,0

### Portfolio performance view

In [5]:
_ = p4.port_view(fancy=True)

### Portfolio and its components relative performances

In [6]:
_ = p4.port_view_all(fancy=True)

## Portfolio performance in terms of total return, maximum drawdown, and RoMaD 

- `RR` - total rate of return
- `DD` - maximum drawdown
- `RoMaD` - return over maximum drawdown (`RR/DD`)
- `DD_date` - maximum drawdown date
- `DD_start` - maximum drawdate stating date
- `DD_end` - maximum drawdown ending date

In [7]:
p4.port_perf(fancy=True)

             RR     DD     RoMaD     DD_date    DD_start      DD_end  DD_days
symbol
UnivPort  13.19 -25.95  0.508337  2020-03-23  2020-02-19  2020-05-11       82
VGT       19.83 -35.07  0.565387  2022-10-14  2021-12-27         NaN      550
XLV       14.16 -28.40  0.498605  2020-03-23  2020-01-22  2020-07-15      175
ONEQ      16.63 -35.23  0.472037  2022-12-28  2021-11-19         NaN      588
SPY       13.58 -33.72  0.402723  2020-03-23  2020-02-19  2020-08-10      173
GLD        1.17 -42.11  0.027880  2015-12-17  2012-10-04  2020-07-22     2848

### Portfolio drawdowns (default - the first 5 largest)

- `DD` - value of the drawdown (percent)
- `Date` - drawdown date
- `Start` - drawdown starting date
- `End` - drawdown ending date

In [8]:
p4.port_drawdown(fancy=True)

       DD        Date       Start         End  NrDays
No
1  -25.95  2020-03-23  2020-02-19  2020-05-11      82
2  -23.10  2022-10-14  2021-12-27         NaN     550
3  -15.54  2018-12-24  2018-10-03  2019-02-04     124
4  -11.02  2015-09-29  2015-07-17  2016-04-19     277
5   -9.37  2020-09-23  2020-09-02  2020-11-16      75

### Portfolio annual (calendar) rate of returns

>Note: the first and last year may not be a full calendar year.

In [9]:
p4.port_annual_returns(fancy=True)

### Portfolio monthly (clandar) rate of returns

In [10]:
p4.port_monthly_returns(fancy=True)

### Portfolio returns per reinvestment period 

- `Droll` - rolling date (rebalansing is assumed to be at the closing of the rolling date)
- `Dfinx` - fixing date (the most recent historical date included in the weights computations - last closing date)
- `RR` - portfolio rate of return on the rolling period starting on `Droll`
- *rest of the columns* - prevailing portfolio weights

In [11]:
p4.port_period_returns(fancy=True)

        Droll       Dfix     RR    VGT    SPY    XLV    GLD   ONEQ
0  2015-06-25 2015-06-24  -7.77  20.00  20.00  20.00  20.00  20.00
1  2015-09-25 2015-09-24   4.15  19.98  19.96  19.92  20.17  19.97
2  2015-12-28 2015-12-24   0.70  20.12  20.05  19.97  19.81  20.05
3  2016-03-28 2016-03-24   0.64  20.08  20.03  19.76  20.24  19.88
4  2016-06-27 2016-06-24   7.94  19.95  19.99  19.80  20.45  19.80
5  2016-09-27 2016-09-26   0.96  20.14  19.95  19.72  20.26  19.93
6  2016-12-27 2016-12-23   7.45  20.31  20.17  19.64  19.77  20.11
7  2017-03-28 2017-03-27   4.16  20.36  20.06  19.64  19.86  20.09
8  2017-06-27 2017-06-26   2.64  20.44  20.03  19.73  19.66  20.14
9  2017-09-26 2017-09-25   6.53  20.45  20.03  19.68  19.73  20.11
10 2017-12-26 2017-12-22   2.97  20.65  20.09  19.57  19.46  20.22
11 2018-03-26 2018-03-23   4.41  20.70  19.98  19.45  19.63  20.23
12 2018-06-26 2018-06-25   4.02  20.81  20.02  19.50  19.31  20.35
13 2018-09-25 2018-09-24 -11.59  20.97  20.05  19.68  18.96  20.34
14 2018-12-26 2018-12-24  18.39  20.64  19.90  19.71  19.69  20.05
15 2019-03-26 2019-03-25   1.21  20.95  19.95  19.57  19.32  20.21
16 2019-06-25 2019-06-24   1.42  20.99  19.95  19.50  19.36  20.20
17 2019-09-25 2019-09-24  10.73  20.99  19.93  19.37  19.55  20.15
18 2019-12-26 2019-12-24  -9.52  21.15  19.92  19.50  19.21  20.23
19 2020-03-26 2020-03-25  25.03  21.08  19.59  19.28  19.96  20.10
20 2020-06-25 2020-06-24   4.05  21.33  19.56  19.18  19.57  20.36
21 2020-09-25 2020-09-24  12.75  21.41  19.56  19.10  19.53  20.40
22 2020-12-28 2020-12-24   0.43  21.60  19.60  19.02  19.18  20.60
23 2021-03-26 2021-03-25   8.75  21.56  19.78  19.11  18.92  20.63
24 2021-06-25 2021-06-24   2.58  21.67  19.78  19.12  18.74  20.69
25 2021-09-27 2021-09-24   6.30  21.78  19.79  19.16  18.57  20.70
26 2021-12-28 2021-12-27  -3.75  21.91  19.81  19.15  18.47  20.66
27 2022-03-28 2022-03-25 -12.00  21.66  19.81  19.22  18.85  20.46
28 2022-06-27 2022-06-24  -7.77  21.47  19.77  19.48  19.04  20.25
29 2022-09-27 2022-09-26   5.08  21.45  19.81  19.54  18.92  20.28
30 2022-12-27 2022-12-23   7.06  21.31  19.82  19.76  19.07  20.03
31 2023-03-28 2023-03-27   9.59  21.61  19.72  19.37  19.11  20.19
32 2023-06-27 2023-06-26   2.58  21.85  19.75  19.22  18.83  20.36

### Number of shares per portfolio component for each rolling period

In [12]:
p4.get_nshares()

            GLD  ONEQ  SPY  VGT  XLV  _CASH_
Droll
2015-06-25  178   994   95  182  264       0
2015-09-25  169   996   96  183  268       0
2015-12-28  187   981   95  179  268       0
2016-03-28  169  1032   96  182  285       0
2016-06-27  158  1040   96  186  279       0
2016-09-27  170  1031  100  181  292       0
2016-12-27  194   989   94  174  299       0
2017-03-28  189   995   98  173  300       0
2017-06-27  197   972   98  168  291       0
2017-09-26  195   988   99  169  298       0
2017-12-26  210   964   98  162  308       0
2018-03-26  206   988  104  164  327       0
2018-06-26  220   940  101  156  316       0
2018-09-25  243   944  100  151  303       0
2018-12-26  211  1063  109  172  315       0
2019-03-26  227   993  105  156  318       0
2019-06-25  222   985  104  153  321       0
2019-09-25  213  1011  106  154  337       0
2019-12-26  236  1006  108  150  328       0
2020-03-26  206  1090  124  160  369       0
2020-06-25  221   991  121  147  368       0
2020-09-25  225   992  122  146  380       0
2020-12-28  246   937  120  139  386       0
2021-03-26  268   942  116  141  382       0
2021-06-25  280   918  115  137  378       0
2021-09-27  292   909  114  132  372       0
2021-12-28  300   919  114  129  374       0
2022-03-28  273   979  116  138  373       0
2022-06-27  258  1028  117  144  347       0
2022-09-27  268  1026  117  145  344       0
2022-12-27  256  1094  116  150  326       0
2023-03-28  254  1057  120  141  366       0
2023-06-27  278  1025  121  135  386       0

### Other accounting informations

- `Droll` - the start of the rolling period (the end is the next period starting date)
- *portfolio symbols* - number of shares per portfolio component
- `cash_invst` - Dollar equivalent of the shares on the `Droll` date
- `cash_roll` - amount of uninvested cash rolled to the next period. A negative value indicates that the investor need to add this cash amount in order to execute the rolling. The main reasons for these small cash amounts are shares price differential between the fixing (computations) and rolling (execution) dates, as well as rounding to an integer the number of shares.
- `cash_divd` - amount of cash collected form dividend payments during the rolling period (it is an approximation considering the ex-dividend day as the dividend pay day - in practice between these dates could be a gap of a few days or even few weeks).

Note: the value of `cash_roll` can be minimized if,
1. set fixing date to be the same as the rolling date (implies the ability to run the portfolio optimization and execute the rolling transactions close to the end of trading day)
2. a large initial capital will lower, in a relative bases, the impact of rounding to an integer the number of shares.

In [13]:
p4.get_account(fancy=True)

            GLD  ONEQ  SPY  VGT  XLV  _CASH_  cash_invst  cash_roll  cash_divd
Droll
2015-06-25  178   994   95  182  264     0.0    99923.14      76.86       0.00
2015-09-25  169   996   96  183  268     0.0    91764.49     863.18     396.01
2015-12-28  187   981   95  179  268     0.0    96884.54     232.27     271.30
2016-03-28  169  1032   96  182  285     0.0    97180.90      -1.86     289.09
2016-06-27  158  1040   96  186  279     0.0    96024.30    1553.60     304.14
2016-09-27  170  1031  100  181  292     0.0   107541.68    -665.27     321.15
2016-12-27  194   989   94  174  299     0.0   105975.03    -254.85     374.57
2017-03-28  189   995   98  173  300     0.0   114330.33    -402.24     276.80
2017-06-27  197   972   98  168  291     0.0   117613.88     901.94     271.02
2017-09-26  195   988   99  169  298     0.0   122896.61     110.57     330.48
2017-12-26  210   964   98  162  308     0.0   130305.71     -15.23     453.13
2018-03-26  206   988  104  164  327     0.0   137233.33   -3363.05     303.56
2018-06-26  220   940  101  156  316     0.0   136517.14    -107.94     304.05
2018-09-25  243   944  100  151  303     0.0   145292.23     174.00     498.41
2018-12-26  211  1063  109  172  315     0.0   134164.74   -5290.18     438.50
2019-03-26  227   993  105  156  318     0.0   147688.54    -721.65     413.59
2019-06-25  222   985  104  153  321     0.0   152133.93    1307.92     475.75
2019-09-25  213  1011  106  154  337     0.0   157680.73    -138.52     358.51
2019-12-26  236  1006  108  150  328     0.0   174434.97   -1030.42     943.95
2020-03-26  206  1090  124  160  369     0.0   164053.69   -8198.29     712.28
2020-06-25  221   991  121  147  368     0.0   189284.14   -1711.21     513.78
2020-09-25  225   992  122  146  380     0.0   205173.02   -3204.09     509.95
2020-12-28  246   937  120  139  386     0.0   227446.44    -998.93     573.09
2021-03-26  268   942  116  141  382     0.0   232560.87   -3033.79     452.51
2021-06-25  280   918  115  137  378     0.0   248365.64    -697.27     492.87
2021-09-27  292   909  114  132  372     0.0   254785.37    1598.89     420.61
2021-12-28  300   919  114  129  374     0.0   273689.64    1449.60     707.12
2022-03-28  273   979  116  138  373     0.0   265691.45   -1159.79     466.71
2022-06-27  258  1028  117  144  347     0.0   229822.19     654.92     541.28
2022-09-27  268  1026  117  145  344     0.0   214526.08    -265.29     465.11
2022-12-27  256  1094  116  150  326     0.0   223459.56    1024.69     779.48
2023-03-28  254  1057  120  141  366     0.0   241076.06     300.48     559.31
2023-06-27  278  1025  121  135  386     0.0   265799.54   -2224.22     490.06

# Universal Portfolio - weights evaluation on a fixing date

This is an example of how to evaluate efficiently the portfolio weights in a fixing date.
It follow a similar procedure as any other portfolio weights evaluation.

We will reuse the `mktdata` previously collected in cell [3].

We star by setting the universal portfolio from a fixing schedule. Later will do a similar computation where the universal portfolio will be set from a hard given fixing date.

### Set a fixing schedule 

For Universal portfolio, the computations of the weights in the fixing date requires the knowledge of all the previous 
fixing dates (as well as market data on these dates). We accomplish this by using `azapy.schedule_simple` function.

- `sdate` - start date of available historical data. The schedule start date will be greater but as close is possible to this date. 
- `edate`- end date of available historical data. The schedule end date is smaller but as close is possible to this date.
- `freq` - fixing frequency. It could be `M` for monthly or `Q` for quarterly.
- `noffset` - rolling date offset - number of business days offset form the last business day of the period (monthly or quarterly).
- `fixoffset` - fixing date offset in business days relative to the rolling date

In [14]:
fixing_schedule = az.schedule_simple(sdate, edate, 
                                     freq='M', noffset=-5, fixoffset=0)
fixing_schedule

         Droll       Dfix
0   2012-01-24 2012-01-24
1   2012-02-22 2012-02-22
2   2012-03-23 2012-03-23
3   2012-04-23 2012-04-23
4   2012-05-23 2012-05-23
..         ...        ...
134 2023-03-24 2023-03-24
135 2023-04-21 2023-04-21
136 2023-05-23 2023-05-23
137 2023-06-23 2023-06-23
138 2023-07-24 2023-07-24

[139 rows x 2 columns]

## Set the `azapy.UniversalEngine` class from a fixing schedule

Alternatively, the UniversalEngine object can be set from a hard given fixing date (we will use this approach later in this script).

In [15]:
puniv = az.UniversalEngine(mktdata, schedule=fixing_schedule)

### Compute the portfolio weights

- `mc_paths` - are the number of simulations per batch (must be >= 1)
- `nr_batches` - are the number of batches (must be >= 1). Note that the computation is multithreaded with one batch per thread.
- `variance_reduction = True` - default value (the MC will use the antithetic variance reduce implied by the permutations of the basket components)
- `alpha_dirichlet = None` - default value. In this case a uniform random generator of vectors in the M-simplex is used. This is equivalent to a Flat Dirichlet random generator (all alpha set to 1).
- `mc_seed` - random generator seed value
- `verbose` - print out
    * number of MC simulations (`mc_paths * nr_batches * M!` if `variance_reduction = True` and `mc_paths * nr_batches` otherwise, where `M` is the number of portfolio components and `M!` its factorial).
    * simulation time
    
>Note: if `variance_reduction = True` (the default value) then both the effective number of MC simulations and the computation time grow factorial with the number of portfolio components. For large portfolios it is recommended to the impact of this setup.

>Note: multithreading under Python implementation has reduced effect. In our case we get a time reduction around 30%

In [16]:

ww = puniv.getWeights(mc_paths=100, nr_batches=16, mc_seed=42, finalonly=False, verbose=True)

nr simulations: 192000
simulation time: 0.395941

### New portfolio weights

These are in the last raw of `ww`.

>Note: `ww` includes all historical weights (along the fixing schedule) - `finalonly` was set to `False`

In [17]:
ww

symbol           GLD      ONEQ       SPY       VGT       XLV
date
2012-01-24  0.200000  0.200000  0.200000  0.200000  0.200000
2012-02-22  0.200701  0.200245  0.199646  0.200631  0.198777
2012-03-23  0.197935  0.201195  0.200116  0.201778  0.198975
2012-04-23  0.198036  0.200804  0.200038  0.201172  0.199949
2012-05-23  0.197724  0.200750  0.200205  0.200843  0.200478
...              ...       ...       ...       ...       ...
2023-02-21  0.166779  0.207962  0.200435  0.218089  0.206735
2023-03-24  0.167973  0.208123  0.199412  0.219334  0.205159
2023-04-21  0.167363  0.207843  0.199840  0.218890  0.206065
2023-05-23  0.166927  0.208853  0.199543  0.220200  0.204477
2023-06-23  0.165187  0.209900  0.199694  0.221602  0.203617

[138 rows x 5 columns]

## Set the `azapy.UniversalEngine` class

### Build the UniversalEngine object

The fixing schedule is build internally going backward from the fixing date with a step of either 21 (for `freq='M'`) or 63 (for `freq='Q'`). The resulting schedule is approximatively equivalent with the one returned by `azapy.shedule_simple` function (that is using a business calendar and in general is more sophisticated).

In [18]:
puniv2 = az.UniversalEngine(mktdata, freq='M')

###  Weights computation - same as before

In [19]:
ww = puniv2.getWeights(mc_paths=100, nr_batches=16, mc_seed=42, verbose=True)
print(ww)

nr simulations: 192000
simulation time: 0.432627
symbol
GLD     0.163962
ONEQ    0.210017
SPY     0.200289
VGT     0.222381
XLV     0.203350
Name: 2023-06-30 00:00:00, dtype: float64

## Set the `azapy.UniversalEngine` class with a Dirichlet random generator

We start by defining the Dirichlet alpha coefficient (must be between 0 and 1)

Here we choose all to be equal to the inverse of the number of portfolio components

In [20]:
dirichlet_alpha = [1 / len(symb)] * len(symb)

### Computation of the weights 

We start by passing the `dirichlet_alpha` coefficients to the constructor.

The rest is the same a above.

>Note: setting all alpha to 1 is equivalent to using a uniform random generator of vectors in the M-simplex of portfolio weights.

In [21]:
puniv2 = az.UniversalEngine(mktdata, freq='M', dirichlet_alpha=dirichlet_alpha)
ww = puniv2.getWeights(mc_paths=100, nr_batches=16, mc_seed=42, verbose=True)
print(ww)

nr simulations: 192000
simulation time: 0.429335
symbol
GLD     0.109668
ONEQ    0.224763
SPY     0.195886
VGT     0.265875
XLV     0.203808
Name: 2023-06-30 00:00:00, dtype: float64